services:
  - type: web
    name: mitras-service
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn mitras.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DB_URL
        value: YOUR_POSTGRES_CONNECTION_STRING
      - key: EMBEDDING_MODEL
        value: text-embedding-gecko-001
      - key: GENERATION_MODEL
        value: gemini-2.5-pro
      - key: TOP_K
        value: "6"
      - key: MAX_CHUNK_TOKENS
        value: "400"
